# Generated by Django 5.1.15 on 2026-06-16 06:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('target_domain', models.CharField(blank=True, max_length=255)),
                ('api_subdomain', models.CharField(default='api', max_length=64)),
                ('app_subdomain', models.CharField(default='app', max_length=64)),
                ('automation_agent', models.CharField(blank=True, max_length=128)),
                ('completed_steps', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setup_transfer', to='organizations.organization')),
            ],
            options={
                'db_table': 'setup_transfers',
            },
        ),
        migrations.CreateModel(
            name='OrganizationDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=255)),
                ('domain_type', models.CharField(choices=[('APP', 'Dashboard (app)'), ('API', 'API (api)')], max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending DNS'), ('VERIFYING', 'Verifying'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('verification_token', models.CharField(blank=True, max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='organizations.organization')),
            ],
            options={
                'db_table': 'organization_domains',
                'unique_together': {('organization', 'hostname')},
            },
        ),
    ]
