# Generated by Django 5.2.15 on 2026-06-17 05:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('amount_minor', models.PositiveIntegerField()),
                ('currency', models.CharField(default='ugx', max_length=3)),
                ('frequency', models.CharField(choices=[('ONE_TIME', 'One time'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=16)),
                ('vat_inclusive', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_products', to='organizations.organization')),
            ],
            options={
                'db_table': 'collection_products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SaccoMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_number', models.CharField(max_length=32)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('momo_network', models.CharField(choices=[('MTN', 'MTN'), ('AIRTEL', 'Airtel'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=16)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sacco_members', to='organizations.organization')),
            ],
            options={
                'db_table': 'sacco_members',
                'ordering': ['member_number'],
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('amount_minor', models.PositiveIntegerField()),
                ('currency', models.CharField(default='ugx', max_length=3)),
                ('rail', models.CharField(default='MOBILE_MONEY', max_length=32)),
                ('provider', models.CharField(choices=[('FLUTTERWAVE', 'Flutterwave'), ('PESAPAL', 'Pesapal')], default='FLUTTERWAVE', max_length=16)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='INITIATED', max_length=16)),
                ('provider_reference', models.CharField(max_length=128, unique=True)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('purpose', models.CharField(blank=True, max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_intents', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='organizations.organization')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to='sacco.collectionproduct')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='sacco.saccomember')),
            ],
            options={
                'db_table': 'payment_intents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('ADJUSTMENT', 'Adjustment'), ('REFUND', 'Refund')], max_length=16)),
                ('amount_minor', models.PositiveIntegerField()),
                ('balance_after', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('external_reference', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='organizations.organization')),
                ('payment_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='sacco.paymentintent')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='sacco.saccomember')),
            ],
            options={
                'db_table': 'ledger_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='saccomember',
            constraint=models.UniqueConstraint(fields=('organization', 'member_number'), name='uniq_org_member_number'),
        ),
        migrations.AddConstraint(
            model_name='saccomember',
            constraint=models.UniqueConstraint(fields=('organization', 'phone'), name='uniq_org_member_phone'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='uniq_org_idempotency_key'),
        ),
    ]
