# Generated by Django 5.1.15 on 2026-06-16 05:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('cipc_registration_number', models.CharField(blank=True, max_length=32, null=True)),
                ('vat_number', models.CharField(blank=True, max_length=16, null=True)),
                ('province', models.CharField(choices=[('GAUTENG', 'Gauteng'), ('WESTERN_CAPE', 'Western Cape'), ('KWAZULU_NATAL', 'KwaZulu-Natal'), ('EASTERN_CAPE', 'Eastern Cape'), ('LIMPOPO', 'Limpopo'), ('MPUMALANGA', 'Mpumalanga'), ('NORTH_WEST', 'North West'), ('FREE_STATE', 'Free State'), ('NORTHERN_CAPE', 'Northern Cape')], default='GAUTENG', max_length=32)),
                ('industry_sector', models.CharField(blank=True, max_length=255)),
                ('popia_consent_at', models.DateTimeField(blank=True, null=True)),
                ('fica_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('fica_verified_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('payfast_token', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MEMBER', 'Member'), ('VIEWER', 'Viewer')], default='MEMBER', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organizations.organization')),
            ],
            options={
                'db_table': 'memberships',
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
