# Generated by Django 5.1.15 on 2026-06-16 05:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('SUBSCRIPTION_CREATED', 'Subscription Created'), ('SUBSCRIPTION_UPDATED', 'Subscription Updated'), ('SUBSCRIPTION_CANCELED', 'Subscription Canceled'), ('INVOICE_PAID', 'Invoice Paid'), ('INVOICE_FAILED', 'Invoice Failed'), ('PAYMENT_SUCCEEDED', 'Payment Succeeded'), ('PAYMENT_FAILED', 'Payment Failed'), ('CHECKOUT_COMPLETED', 'Checkout Completed'), ('EFT_PENDING', 'EFT Pending'), ('PAYSHAP_RECEIVED', 'PayShap Received')], max_length=32)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('vat_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='zar', max_length=3)),
                ('payment_provider', models.CharField(blank=True, choices=[('STRIPE', 'Stripe'), ('PAYFAST', 'PayFast'), ('OZOW', 'Ozow'), ('PEACH_PAYMENTS', 'Peach Payments')], max_length=32, null=True)),
                ('payment_rail', models.CharField(blank=True, choices=[('CARD', 'Card'), ('EFT', 'EFT'), ('INSTANT_EFT', 'Instant EFT'), ('DEBIT_ORDER', 'Debit Order'), ('PAYSHAP', 'PayShap'), ('RNCS', 'Capitec Pay / RNCS')], max_length=32, null=True)),
                ('external_event_id', models.CharField(max_length=128, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_events', to='organizations.organization')),
            ],
            options={
                'db_table': 'payment_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_subscription_id', models.CharField(max_length=128, unique=True)),
                ('external_price_id', models.CharField(blank=True, max_length=128, null=True)),
                ('payment_provider', models.CharField(choices=[('STRIPE', 'Stripe'), ('PAYFAST', 'PayFast'), ('OZOW', 'Ozow'), ('PEACH_PAYMENTS', 'Peach Payments')], default='PAYFAST', max_length=32)),
                ('plan_tier', models.CharField(choices=[('STARTER', 'Starter'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TRIALING', 'Trialing'), ('PAST_DUE', 'Past Due'), ('CANCELED', 'Canceled'), ('INCOMPLETE', 'Incomplete'), ('UNPAID', 'Unpaid')], max_length=16)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='zar', max_length=3)),
                ('vat_cents', models.PositiveIntegerField(default=0)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.organization')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
    ]
