# Generated by Django 5.1.15 on 2026-06-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentevent',
            name='settlement_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SETTLED', 'Settled'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='SETTLED', max_length=16),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='payment_rail',
            field=models.CharField(blank=True, choices=[('CARD', 'Card'), ('EFT', 'EFT'), ('INSTANT_EFT', 'Instant EFT'), ('DEBIT_ORDER', 'Debit Order'), ('PAYSHAP', 'PayShap'), ('RNCS', 'Capitec Pay / RNCS'), ('MOBILE_MONEY', 'Mobile Money'), ('USSD', 'USSD'), ('AGENT_CASH', 'Agent Cash')], max_length=32, null=True),
        ),
    ]
