# Generated by Django 5.2.15 on 2026-06-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_fxratesnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentevent',
            name='currency',
            field=models.CharField(default='ugx', max_length=3),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=models.CharField(default='ugx', max_length=3),
        ),
    ]
