# Generated by Django 5.2.15 on 2026-06-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_paymentevent_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentevent',
            name='payment_provider',
            field=models.CharField(blank=True, choices=[('STRIPE', 'Stripe'), ('PAYFAST', 'PayFast'), ('OZOW', 'Ozow'), ('PEACH_PAYMENTS', 'Peach Payments'), ('FLUTTERWAVE', 'Flutterwave'), ('PESAPAL', 'Pesapal')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_provider',
            field=models.CharField(choices=[('STRIPE', 'Stripe'), ('PAYFAST', 'PayFast'), ('OZOW', 'Ozow'), ('PEACH_PAYMENTS', 'Peach Payments'), ('FLUTTERWAVE', 'Flutterwave'), ('PESAPAL', 'Pesapal')], default='PAYFAST', max_length=32),
        ),
    ]
